CREATE TABLE IF NOT EXISTS users
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email CHAR(50) NOT NULL,
  password CHAR(60) NOT NULL COMMENT 'encrypted value',
  first_name VARCHAR(20) NOT NULL,
  middle_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS roles
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  role CHAR(5) NOT NULL COMMENT 'default roles: admin, user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (role)
);

CREATE TABLE IF NOT EXISTS user_roles
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS manufacturers
(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  manufacturer VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (manufacturer)
);

CREATE TABLE IF NOT EXISTS models
(
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  model VARCHAR(30) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (model)
);

CREATE TABLE IF NOT EXISTS make_years
(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  year YEAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (year)
);

CREATE TABLE IF NOT EXISTS payment_types
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_type CHAR(4) NOT NULL COMMENT 'Types:Cash, card',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (payment_type)
);

CREATE TABLE IF NOT EXISTS card_providers
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  card_provider VARCHAR(30) NOT NULL COMMENT 'e.g. Visa, MasterCard',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (card_provider)
);

CREATE TABLE IF NOT EXISTS accessories
(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  accessory VARCHAR(20) NOT NULL COMMENT 'e.g. child seat, GPS',
  available_qty INT NOT NULL,
  reserved_qty INT NOT NULL COMMENT 'quantities used in ongoing reservations',
  total_qty INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (accessory)
);

CREATE TABLE IF NOT EXISTS car_categories
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category CHAR(20) NOT NULL COMMENT 'e.g. SUV, Sedan, Hatchback',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (category)
);

CREATE TABLE IF NOT EXISTS countries
(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  country_code CHAR(2) NOT NULL,
  country_name_en VARCHAR(50) NOT NULL,
  country_nationality_en VARCHAR(50) NOT NULL,
  country_name_ar VARCHAR(50) NOT NULL COLLATE utf8_general_ci,
  country_nationality_ar VARCHAR(50) NOT NULL COLLATE utf8_general_ci,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (country_code)
);

CREATE TABLE IF NOT EXISTS customer_info
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  country_id SMALLINT UNSIGNED NOT NULL,
  CPR INT NOT NULL,
  phone_no VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (country_id) REFERENCES countries(id)
);

CREATE TABLE IF NOT EXISTS cars
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  manufacturer_id SMALLINT UNSIGNED NOT NULL,
  model_id MEDIUMINT UNSIGNED NOT NULL,
  make_year_id SMALLINT UNSIGNED NOT NULL,
  category_id TINYINT UNSIGNED NOT NULL,
  daily_rental_price NUMERIC(6,3) NOT NULL,
  image VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (manufacturer_id) REFERENCES manufacturers(id),
  FOREIGN KEY (model_id) REFERENCES models(id),
  FOREIGN KEY (make_year_id) REFERENCES make_years(id),
  FOREIGN KEY (category_id) REFERENCES car_categories(id)
);

CREATE TABLE IF NOT EXISTS customer_addresses
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  customer_id INT UNSIGNED NOT NULL,
  address VARCHAR(250) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (customer_id) REFERENCES customer_info(id),
  UNIQUE (address)
);

CREATE TABLE IF NOT EXISTS customer_cards
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  card_provider_id TINYINT UNSIGNED NOT NULL,
  customer_id INT UNSIGNED NOT NULL,
  card_number CHAR(60) NOT NULL,
  expiry_date DATE NOT NULL,
  security_digits CHAR(60) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (card_provider_id) REFERENCES card_providers(id),
  FOREIGN KEY (customer_id) REFERENCES customer_info(id),
  UNIQUE (card_number)
);

CREATE TABLE IF NOT EXISTS customer_reservations
(
  id INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  customer_id INT UNSIGNED NOT NULL,
  payment_type_id TINYINT UNSIGNED NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_rental_cost NUMERIC(8,3) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (customer_id) REFERENCES customer_info(id),
  FOREIGN KEY (payment_type_id) REFERENCES payment_types(id)
);

CREATE TABLE IF NOT EXISTS reservation_cars
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reservation_id INT UNSIGNED NOT NULL,
  car_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (reservation_id) REFERENCES customer_reservations(id),
  FOREIGN KEY (car_id) REFERENCES cars(id)
);

CREATE TABLE IF NOT EXISTS reservation_accessories
(
  id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  accessory_id SMALLINT UNSIGNED NOT NULL,
  reservation_id INT UNSIGNED NOT NULL,
  reserve_qty TINYINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (accessory_id) REFERENCES accessories(id),
  FOREIGN KEY (reservation_id) REFERENCES customer_reservations(id)
);

CREATE TABLE IF NOT EXISTS most_popular_cars_report
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  car_id INT UNSIGNED NOT NULL,
  reservations_count INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (car_id) REFERENCES cars(id)
);

CREATE TABLE IF NOT EXISTS sales_revenue_report
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  transaction_id INT UNSIGNED NOT NULL,
  transaction_date DATE NOT NULL,
  transaction_amount NUMERIC(8,3) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (transaction_id) REFERENCES customer_reservations(id)
);